### ISSUE TITLE
White icons on white background

### ISSUE THREAD

**Issue by lllmio** [kennethso168/AdvancedPowerMenu#1]
I'm author of this post on xda
http://forum.xda-developers.com/showpost.php?p=45634014&postcount=117
I've attached screenshot of how does it look like. I'm also Android developer (not very expirienced), so I can help you at least with testing of this functionality.
![screenshot_2013-09-16-08-00-06 1](https://f.cloud.github.com/assets/1689966/1156204/fd7f1e44-1f80-11e3-891f-0b8882f6069b.png)
P.S.: I've tried to detect background color, but failed :)

**Comment by kennethso168** [comment]
Well the colors are really a bit not normal ( but look nice ) I'll try to
provide a 'colorful' set of icons in the future then.

**Comment by kennethso168** [comment]
Now you may try out the newest v5.0a_r1 alpha release
You can go to my app and set "Color theme for icons" to colorful. Then reboot the device.
See if this can fix the issue.

**Comment by lllmio** [comment]
It looks better now, but there are some small problems:
1) when using dark theme: dark icons in "reset" menu should be white
![screenshot_2013-09-22-15-01-44](https://f.cloud.github.com/assets/1689966/1187499/ebb973f6-237e-11e3-88f3-b5a24bd623b2.png)
2) when usinc colorful theme: green reboot icon is eyekilling (too bright)
![screenshot_2013-09-22-14-43-58](https://f.cloud.github.com/assets/1689966/1187501/0f21e4b8-237f-11e3-80a8-415b8821496a.png)
P.S: green icon looks brighter on device than on screenshot

**Comment by kennethso168** [comment]
1. If I did this I would go to far just for some eye-candy
2. That green (#00ff00) is the characteristic color for my app (you can see the app icon and it has the same green color.
   I'd focus on functionality now instead of aesthetics. So please don't expect any fixes to these issues soon. Sorry.
   Issue closed.
