### ISSUE TITLE
Option: Remove ringermodes from powermenu

### ISSUE THREAD

**Issue by ghost** [kennethso168/AdvancedPowerMenu#25]
Option: Remove ringermodes from powermenu that appear on phone UI (only?).

I mean the three toggle buttons for switching between silent, vibration and normal audio mode. I can post a picture of that if you need it.

I studied your code, and it appears not to be very hard to do but i lack the immediate knowledge and haven't got the workspace set up. Maybe you want to add this feature yourself or maybe you want to point me into some direction.

Thanks for the plugin! I love it :)

**Comment by kennethso168** [comment]
Done in v9.1.x
